# Generated by Django 6.0.6 on 2026-09-08 12:21

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0015_alter_variable_value_max_alter_variable_value_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending build'), ('building', 'Building'), ('ready', 'Ready'), ('stale', 'Stale'), ('failed', 'Failed'), ('no_data', 'No data')], db_index=True, default='pending', max_length=20)),
                ('built_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', help_text='The claim token held by the copy currently building, not merely the worker.', max_length=100)),
                ('error', models.TextField(blank=True)),
                ('input_fingerprint', models.CharField(blank=True, default='', editable=False, help_text='Identity of the inputs the last successful build read. A build whose inputs still fingerprint the same has nothing to do.', max_length=200)),
                ('area', models.SlugField(help_text='The area name readers ask for, unique within the organisation. It is the filename under latest/ and a directory under the prefix, so changing it strands the old one.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled publications are skipped by the sweep and dropped from jsonformat.json.')),
                ('west', models.FloatField(help_text='Western edge, degrees east.')),
                ('south', models.FloatField(help_text='Southern edge, degrees north.')),
                ('east', models.FloatField(help_text='Eastern edge, degrees east.')),
                ('north', models.FloatField(help_text='Northern edge, degrees north.')),
                ('grid_id', models.CharField(blank=True, default='', editable=False, help_text='MD5 of the coordinate bytes, pinned at the first build. rawdataforecaster caches its s2 index under this, so a build that produces a different one is refused rather than published.', max_length=32)),
                ('point_count', models.PositiveIntegerField(default=0, editable=False)),
                ('published_version', models.BigIntegerField(blank=True, editable=False, help_text='ref_epoch_seconds * 100 + revision — the integer latest/<area> holds.', null=True)),
                ('published_reference_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('published_step_count', models.PositiveIntegerField(default=0, editable=False)),
                ('published_parameters', models.JSONField(blank=True, default=list, editable=False, help_text="Forti internal names actually written, which vary with the run's step spacing.")),
                ('time_until_next_hours', models.PositiveIntegerField(blank=True, help_text="Override for complete.json's time_until_next. Left blank it is derived from the gap between the last two closed runs.", null=True)),
                ('collection', models.OneToOneField(help_text='The forecast collection this area publishes. Must be public.', on_delete=django.db.models.deletion.CASCADE, related_name='forti_publication', to='georivacore.collection')),
            ],
            options={
                'verbose_name': 'Forti publication',
                'ordering': ['collection__slug'],
            },
        ),
        migrations.CreateModel(
            name='FortiPublicationBuildLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('build', 'Build'), ('gc', 'Garbage collection')], max_length=10)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('error', models.TextField(blank=True)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('point_count', models.PositiveIntegerField(default=0)),
                ('parameter_count', models.PositiveIntegerField(default=0)),
                ('objects_written', models.PositiveIntegerField(default=0)),
                ('versions_pruned', models.PositiveIntegerField(default=0)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to='georiva_publisher_forti.fortipublication')),
            ],
            options={
                'verbose_name': 'Forti publication build log',
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='fortipublication',
            index=models.Index(fields=['status'], name='idx_forti_pub_status'),
        ),
        migrations.AddIndex(
            model_name='fortipublicationbuildlog',
            index=models.Index(fields=['started_at'], name='idx_forti_log_started'),
        ),
    ]
