# Generated by Django 6.0.6 on 2026-09-15 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georiva_publisher_forti', '0003_fortipublication_collection_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortipublication',
            name='generation',
            field=models.PositiveSmallIntegerField(default=0, help_text='Counts changes to the published bytes that are not changes to the run. rawdataforecaster reloads only on a strictly greater version, so republishing one run under a changed configuration needs a term the run does not supply — otherwise the correct new bytes sit under the stamp the reader already holds and are never loaded. Raise it by one and republish. It resets itself when a new run is published, because a new run at generation 0 already outranks any generation of the one before it.', validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='published_version',
            field=models.BigIntegerField(blank=True, editable=False, help_text="run.version * 100 + generation — the integer latest/<area key> holds. The run's own half is ref_epoch_seconds * 100 + revision, so the whole stamp orders by model time, then by republish of that run, then by configuration generation.", null=True),
        ),
    ]
