# Generated by Django 6.0.6 on 2026-09-18 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georiva_publisher_forti', '0005_forti_variable_mapping'),
        ('georivacore', '0015_alter_variable_value_max_alter_variable_value_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortipublication',
            name='collection',
            field=models.OneToOneField(help_text='The forecast collection to publish. Only forecast collections can be published.', on_delete=django.db.models.deletion.CASCADE, related_name='forti_publication', to='georivacore.collection'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='east',
            field=models.FloatField(help_text='Longitude, in degrees.', verbose_name='East edge'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='generation',
            field=models.PositiveSmallIntegerField(default=0, help_text='Usually leave at 0. Raise it by 1 to republish the current run after changing settings. Resets when a new run is published.', validators=[django.core.validators.MaxValueValidator(99, message='At most %(limit_value)s republishes of one run. Wait for the next run, which resets the counter.')], verbose_name='Republish counter'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='grid_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='Fingerprint of the grid of points, fixed at the first publish.', max_length=32, verbose_name='Grid'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Untick to stop publishing this forecast without deleting it.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='north',
            field=models.FloatField(help_text='Latitude, in degrees.', verbose_name='North edge'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='point_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Grid points'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='published_parameters',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='The Forti parameters the last publish included.', verbose_name='Parameters published'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='published_reference_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Forecast run time'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='published_step_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Steps published'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='published_version',
            field=models.BigIntegerField(blank=True, editable=False, help_text='Version number of what was last published. Goes up with every publish.', null=True, verbose_name='Published version'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='slug',
            field=models.SlugField(blank=True, help_text="The name this forecast is served under, e.g. 'kenya'. Leave blank to use the catalog's name. Cannot be changed after the first publish.", verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='south',
            field=models.FloatField(help_text='Latitude, in degrees.', verbose_name='South edge'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='time_until_next_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to work it out from the gap between the last two runs.', null=True, verbose_name='Hours until the next run'),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='', help_text="Who can see this forecast. Leave blank to use the collection's setting. It can be more restricted than the collection, never less.", max_length=10),
        ),
        migrations.AlterField(
            model_name='fortipublication',
            name='west',
            field=models.FloatField(help_text='Longitude, in degrees.', verbose_name='West edge'),
        ),
        migrations.AlterField(
            model_name='fortivariablemapping',
            name='slot',
            field=models.CharField(choices=[('2t', '2t'), ('2d', '2d'), ('msl', 'msl'), ('wind_speed_10m', 'wind_speed_10m'), ('wind_dir_10m', 'wind_dir_10m'), ('10fg', '10fg'), ('tcc', 'tcc'), ('tp', 'tp')], help_text='The Forti parameter this variable is published as.', max_length=32, verbose_name='Forti parameter'),
        ),
        migrations.AlterField(
            model_name='fortivariablemapping',
            name='variable',
            field=models.ForeignKey(blank=True, help_text='The variable to publish as this Forti parameter. Leave blank if there is none yet.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='forti_slots', to='georivacore.variable'),
        ),
    ]
